-- MySQL Script generated by MySQL Workbench
-- Fri May 12 12:40:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Borojo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Borojo` ;

-- -----------------------------------------------------
-- Schema Borojo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Borojo` DEFAULT CHARACTER SET utf8mb4 ;
USE `Borojo` ;

-- -----------------------------------------------------
-- Table `Borojo`.`Compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Borojo`.`Compras` ;

CREATE TABLE IF NOT EXISTS `Borojo`.`Compras` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Factura` INT NOT NULL,
  `Cantidad` INT NULL,
  `Observacion` VARCHAR(50) NULL,
  `Proveedor` VARCHAR(45) NULL,
  `IdInsumos` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Borojo`.`Existencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Borojo`.`Existencias` ;

CREATE TABLE IF NOT EXISTS `Borojo`.`Existencias` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Cantidad` INT NOT NULL,
  `IdInsumos` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Borojo`.`GastosProduccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Borojo`.`GastosProduccion` ;

CREATE TABLE IF NOT EXISTS `Borojo`.`GastosProduccion` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdExistencia` INT NULL,
  `IdProduccion` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Borojo`.`Insumos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Borojo`.`Insumos` ;

CREATE TABLE IF NOT EXISTS `Borojo`.`Insumos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `UnidadPeso` INT NULL,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Borojo`.`Producciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Borojo`.`Producciones` ;

CREATE TABLE IF NOT EXISTS `Borojo`.`Producciones` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL,
  `Cantidad` INT NULL,
  `IdProducto` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Borojo`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Borojo`.`Productos` ;

CREATE TABLE IF NOT EXISTS `Borojo`.`Productos` (
  `Codigo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Presentacion` VARCHAR(45) NULL,
  `Peso` INT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
